services:
  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=softjobs
    ports:
      - "5678:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
